# Change these first
owner: MattiaPARRINELLO # Your GitHub organization or username
repo: Uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: SoBot
    url: https://sobot.fr
  - name: Bot Hosting
    url: $RASP
  - name: Discord
    url: https://discord.sobot.fr
  - name: DataBase 1
    url: $DB1
  - name: DataBase 2
    url: $DB2
  - name: Control Panel
    url: $CP


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /Uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SoBot
  introTitle: "Voici le site de Uptime de SoBot, ici vous pourez voir à touts moment l'état de chaques site de SoBot"
  introMessage: SALUT
  navbar:
    - title: Status
      href: /Uptime
    - title: SoBot
      href: https://sobot.fr
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
