# Change these first
owner: MattiaPARRINELLO # Your GitHub organization or username
repo: Uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: SoBot
    url: https://sobot.fr
  - name: Bot Hosting
    url: $RASP
  - name: Discord
    url: https://discord.sobot.fr
  - name: DataBase 1
    url: $DB1
  - name: DataBase 2
    url: $DB2
  - name: Control Panel
    url: $CP

i18n:
  activeIncidents: "Problèmes actifs"
  allSystemsOperational: "🟩 Tous les systèmes sont opérationels"
  incidentReport: "Incident N°$NUMBER infos →"
  activeIncidentSummary: "Ouvert à $DATE avec $POSTS posts"
  incidentTitle: "Incident N°$NUMBER Details"
  incidentDetails: "Détails de l'incident"
  incidentFixed: "Réparé"
  incidentOngoing: "En cours"
  incidentOpenedAt: "Ouvert à"
  incidentClosedAt: "Fermé à" 
  incidentSubscribe: "S'inscrire aux mises à jour"
  incidentViewOnGitHub: "Voir sur GitHub"
  incidentCommentSummary: "osté à $DATE par $AUTHOR"
  incidentBack: "← Retours à tous les incidents"
  pastIncidents: "Incidents passé"
  pastIncidentsResolved: "Résolus en $MINUTES minutes avec $POSTS posts"
  liveStatus: "Statut en direct"
  overallUptime: "Disponibilité : $UPTIME"
  overallUptimeTitle: "Disponibilité"
  averageResponseTime: "Temps de réponse moyen: $TIMEms"
  averageResponseTimeTitle: "Temps de réponse"
  sevelDayResponseTime: "Temps de réponse au cours des 7 derniers jours"
  responseTimeMs: "Temps de réponse (ms)"
  up: "🟩 Up"
  down: "🟥 Down"
  degraded: "🟨 Dégradé"
  ms: "ms"
  loading: "Chargement"
  navGitHub: "GitHub"
  footer: "Made By SoBot x Upptime"
  rateLimitExceededTitle: "Dépassement de la limite"
  rateLimitExceededIntro: "Vous avez dépassez le nombre de requètes que vous pouvez faire à ce site en une heure, donc vous devez attendre avant de pouvoir acceder à nouveau au site."
  rateLimitExceededWhatDoesErrorMean: "Que signifie cette erreur ?"
  rateLimitExceededErrorMeaning: "Ce site web utilise l'API GitHub pour acceder en à des information en direct sur leurs site. Par default? GitHub autorise chaque IP 60 requetes par heure, que vous avez consomer."
  rateLimitExceededErrorHowCanFix: "Comment le réparer ?"
  rateLimitExceededErrorFix: "Vous pouvez attendre une heure pour que votre interdiction soit levée. Sinon vous pouvez ajouter votre GitHub Personal Access Token qui vas vous donner en plus 5000 requetes pas heure."
  rateLimitExceededGeneratePAT: "Apprenez comment générer un Github Personal Acces Token"
  rateLimitExceededHasSet: "Vous avez déjà un Token ajouté"
  rateLimitExceededRemoveToken: "Retirer le Token"
  rateLimitExceededGitHubPAT: "GitHub Personal Access Token"
  rateLimitExceededCopyPastePAT: "Copier-Coller vote Token"
  rateLimitExceededSaveToken: "Sauvegarder le Token"
  errorTitle: "Une erreur c'est produite"
  errorIntro: "Une erreur s'est produite lors de la tentative d'obtention des derniers détails d'état."
  errorText: "Réésayer dans quelques instants"
  errorHome: "Aller sur la page d'acceuil"
  pastScheduledMaintenance: "Maintenance planifiée antérieure"
  scheduledMaintenance: "Maintenace planifiée"
  scheduledMaintenanceSummaryStarted: "Démarré le $DATE pour $DURATION minutes"
  scheduledMaintenanceSummaryStarts: "Démare le  $DATE pour $DURATION minutes"
  startedAt: "Commencé le"
  startsAt: "Commence le"
  duration: "Durée"
  durationMin: "$DURATION minutes"
  incidentCompleted: "Complétée"
  incidentScheduled: "Planifié"
  #README
  url: "URL"
  status: "Statut"
  history: "Historique"
  responseTimeGraphAlt: "Graphique du temps de réponse"
  responseTime: "Temps de réponse"
  responseTimeDay: "Temps de réponse des 24 dérnières heures"
  responseTimeWeek: "Temps de réponse des 7 dérniers jours"
  responseTimeMonth: "Temps de réponse des 30 dérniers jour"
  responseTimeYear: "Temps de réponse de cette année"
  uptime: "Disponibilité"
  uptimeDay: "Disponibilité des 24 dérnières heures"
  uptimeWeek: "Disponibilité des 7 dérnières jours"
  uptimeMonth: "Disponibilité des 7 dérnières jours"
  uptimeYear: "Disponibilité de cette année"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "🟩 Tout les systèmes sont oppérationels"
  degradedPerformance: "🟨 Performance dégradée"
  completeOutage: "🟥 Complètement Down"
  partialOutage: "🟧 Partièlement Down"

status-website:
  theme: ocean
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /Uptime
  logoUrl: https://i.imgur.com/b8Oj12U.png
  name: SoBot
  introTitle: "Voici le site de Uptime de SoBot, ici vous pourez voir à touts moment l'état de chaques site de SoBot"
  introMessage: SALUT
  navbar:
    - title: Status
      href: /Uptime
    - title: SoBot
      href: https://sobot.fr

  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
