# Change these first
owner: MattiaPARRINELLO# Your GitHub organization or username
repo: Uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Test for HEAD
    method: HEAD
    url: https://www.google.com
  - name: Secret Site
    url: $SECRET_SITE
  - name: TCP ping
    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
   baseUrl: /Uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SoBot
  introTitle: "Voici le site de Uptime de SoBot, ici vous pourez voir à touts moment l'état de chaques site de SoBot"
  introMessage: 
  them: ocean
  navbar:
    - title: Status
      href: /Uptime
    - title: SoBot
      href: https://sobot.fr
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
